"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory $git_branch
$character
"""

right_format = """$time$battery"""
continuation_prompt = '>'
add_newline = false
palette = 'blues'

[palettes.blues]
# that was a lie
red = '#f38ba8'
blue = '#89b4fa'
coral = '#fab387'
weird_orange = '#d8a31a'
ma = '#cba6f7'
lv = '#b4befe'

[character]
success_symbol = '[❯](bold ma)'
error_symbol = '[❯](bold red)'


[battery]
full_symbol = '􀛨  '
charging_symbol = '􀢋  '
discharging_symbol = '􀺶  '
unknown_symbol = '?'
empty_symbol = '􀛪  '
format = '[$symbol$percentage](bold $style)'

[[battery.display]]
threshold = 10
style = 'red'

[[battery.display]]
threshold = 100
style = 'ma'

[time]
disabled = false
format = '[$time]($style)'
use_12hr = false
time_format = '[%H:%M >-< %d/%m]'
style = 'bold ma'

[directory]
format = '[$path](bold $style)'
read_only_style = 'weird_orange'
style = 'ma'
truncation_length = 2

[git_branch]
format = '[\[](bold $style)[$symbol$branch](bold $style)[\]](bold $style)'
style = 'lv'
